# Generated by Django 2.0 on 2019-03-03 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Borrador', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('imagen_blog', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_blog', models.DateField(default=django.utils.timezone.now)),
                ('hora_blog', models.TimeField(default=django.utils.timezone.now)),
                ('linkblog', models.CharField(blank=True, max_length=255, null=True)),
                ('video_blog', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_descripcion', models.CharField(blank=True, max_length=165, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
