# Generated by Django 3.0.6 on 2020-07-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Galeria de Imagenes'},
        ),
    ]
