# Generated by Django 3.0.6 on 2020-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaRestoran',
            fields=[
                ('estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], default='Publicado', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_id', models.AutoField(max_length=9999, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': '1. Carta Restorán',
            },
        ),
        migrations.AlterModelOptions(
            name='carta',
            options={'verbose_name_plural': '2. Carta Delivery'},
        ),
        migrations.AlterField(
            model_name='carta',
            name='estado',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], default='Publicado', max_length=12),
        ),
    ]
